/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Confirm: typeof import('./src/components/modals/Confirm.vue')['default']
    GeneralLoading: typeof import('./src/components/GeneralLoading.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconHeroiconsOutlineBurger: typeof import('~icons/heroicons-outline/burger')['default']
    IconHeroiconsOutlineClose: typeof import('~icons/heroicons-outline/close')['default']
    IconHeroiconsOutlineCross: typeof import('~icons/heroicons-outline/cross')['default']
    IconHeroiconsOutlineExit: typeof import('~icons/heroicons-outline/exit')['default']
    IconHeroiconsOutlineEye: typeof import('~icons/heroicons-outline/eye')['default']
    IconHeroiconsOutlineLocationMarker: typeof import('~icons/heroicons-outline/location-marker')['default']
    IconHeroiconsOutlineMail: typeof import('~icons/heroicons-outline/mail')['default']
    IconHeroiconsOutlineMailicon: typeof import('~icons/heroicons-outline/mailicon')['default']
    IconHeroiconsOutlineMailIcon: typeof import('~icons/heroicons-outline/mail-icon')['default']
    IconHeroiconsOutlineMenu: typeof import('~icons/heroicons-outline/menu')['default']
    IconHeroiconsOutlinePhone: typeof import('~icons/heroicons-outline/phone')['default']
    IconHeroiconsOutlinePin: typeof import('~icons/heroicons-outline/pin')['default']
    IconHeroiconsOutlineSearch: typeof import('~icons/heroicons-outline/search')['default']
    IconHeroiconsOutlineStop: typeof import('~icons/heroicons-outline/stop')['default']
    IconHeroiconsOutlineTrash: typeof import('~icons/heroicons-outline/trash')['default']
    IconHeroiconsOutlineXCircleIcon: typeof import('~icons/heroicons-outline/x-circle-icon')['default']
    IconHeroiconsOutlineXicon: typeof import('~icons/heroicons-outline/xicon')['default']
    IconHeroiconsOutlineXIcon: typeof import('~icons/heroicons-outline/x-icon')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NotFound: typeof import('./src/components/cards/NotFound.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    User: typeof import('./src/components/forms/User.vue')['default']
    UserCard: typeof import('./src/components/cards/UserCard.vue')['default']
    UserDetail: typeof import('./src/components/modals/UserDetail.vue')['default']
  }
}
